// pages/jinxuan/jinxuan.js
var app = getApp()  
Page({  
  data: {  
    navbar: ['分类', '热门', '综合榜','筛选'],  
    currentTab: 0 ,
    drr:[
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index1.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index1.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index1.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index1.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index1.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index1.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index1.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index1.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    }
  ],
  arr:[
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index2.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index2.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index2.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index2.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index2.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index2.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index2.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    },
    {
      "name":"鸿毛饺子",
      "src":"/images/imgs/index2.jpg",
      "money":"36元",
      "mi":"770m",
      "num":"45645"
    }
  ] 
  },  
  navbarTap: function(e){  
    this.setData({  
      currentTab: e.currentTarget.dataset.idx  
    })  
  }  
})  
